### ISSUE TITLE
Make it clearer how to sign up for the mailing list

### ISSUE THREAD

**Issue by Notts90** [codidact/docs#1]
On the codidact / docs Wiki page the email address for the announcements mailing list is listed, however it isn't stated how to actually sign up for the mailing list.

As a user I would normally expect to enter **my** email address and then receive emails from the listed address. If you want users to do something different to that, it should be clearly stated.

Edit: Same issue on the landing page https://github.com/codidact/landing-page/issues/19

**Comment by manassehkatz** [comment]
Sorry about the confusion. There are two ways (aside from list moderator directly doing it directly):

For a list named **announcements@codidact.org**:

* Send a message to announcements-subscribe@codidact.org (The system will Reply with a confirmation message)
* Send a message to announcements-subscribe-user=domain.tld (The system will send a message to user@domain.tld)

[See the official ezmlm documentation for details](https://untroubled.org/ezmlm/manual/Subscribing.html).

So for our own landing page, we should probably have both:

* A web form which accepts an email address and sends a message to subscribe that email address. (Yes, subject to fake subscription requests by "bad guys", but that's why there is a confirmation email which requires a link or Reply to finish the process.)
* A notice saying something like: "To subscribe, send a message to [announcements-subscribe@codidact.org](mailto:announcements-subscribe@codidact.org) or use the form below."

That would cover all situations, including the wacky (but it happens) situation of someone prints or screenshots the page and sends it to someone, so that the recipient doesn't have immediate access to the form directly (as crazy as that sounds), or even just people who find out via email and don't want to open a web browser to do anything (as crazy as *that* sounds).

**Comment by cellio** [comment]
I updated the wiki.  Reassigning for the landing page.

**Comment by mattjbrent** [comment]
@cellio  submitted a PR to address this in the landing page

**Comment by mattjbrent** [comment]
@cellio is this resolved?

**Comment by cellio** [comment]
Yes looks good.
